## g' Filter Table and Math

In [73]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy import odr
from math import log

df = pd.read_csv(r"C:\Users\Jonathan Chavez\OneDrive\Desktop\GBO-Calibration\g'filter.csv",
                 sep=",", encoding='cp1252')#encoding added as solution from encoding as UTF-8

df.head(14)

    id      xCenter  aperture_sum  aperture_sum_err
0    1  2825.058367  2.836636e+06       1836.981328
1    2  2070.508843  3.356012e+04        738.727345
2    3  2333.906270  4.980129e+04        739.948092
3    4  2168.696896  3.062307e+04        721.106685
4    5   417.071420  1.789245e+05        825.557591
5    6  1060.293465  4.171433e+05        956.224585
6    7  1337.309923  4.415587e+04        734.281508
7    8  1993.912750  2.955426e+05        893.942479
8    9  3106.370670  5.385574e+05       1023.843231
9   10  3406.027967  8.528918e+04        767.206503
10  11  3685.485847  1.048790e+06       1254.612425
11  12  3754.036448  8.578675e+05       1172.657060
12  13   798.731120  3.844310e+04        741.732881
13  14  1777.859011  1.019788e+05        789.311690

In [74]:
df['log_sumg'] = -2.5 * np.log10(df['aperture_sum'])
df['magnitude_err'] = 2.5 / (np.log(10) * df['aperture_sum']) * df['aperture_sum_err']

df['log_sumErr_g'] = df.apply(lambda row: f"{row['log_sumg']:.5f} ± {row['magnitude_err']:.5f}", axis=1)
print(df.log_sumErr_g)

0     -16.13201 ± 0.00070
1     -11.31456 ± 0.02390
2     -11.74310 ± 0.01613
3     -11.21512 ± 0.02557
4     -13.13167 ± 0.00501
5     -14.05071 ± 0.00249
6     -11.61247 ± 0.01806
7     -13.67655 ± 0.00328
8     -14.32808 ± 0.00206
9     -12.32723 ± 0.00977
10    -15.05172 ± 0.00130
11    -14.83355 ± 0.00148
12    -11.46205 ± 0.02095
13    -12.52128 ± 0.00840
Name: log_sumErr_g, dtype: object

## i' Filter Table and Math

In [75]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy import odr

df = pd.read_csv(r"C:\Users\Jonathan Chavez\OneDrive\Desktop\GBO-Calibration\i'filter.csv",
                 sep=",", encoding='cp1252')

df.head()

   id      xCenter  aperture_sum  aperture_sum_err
0   1  2830.680412  2.024634e+06       1564.044508
1   2  2075.396365  4.029140e+04        669.371783
2   3  2338.918181  3.912937e+04        656.629031
3   4  2173.533134  2.382374e+04        638.888292
4   5   420.414143  1.424999e+05        738.369770

In [76]:
df['log_sumi'] = -2.5 * np.log10(df['aperture_sum'])
df['magnitude_err'] = 2.5 / (np.log(10) * df['aperture_sum']) * df['aperture_sum_err']

df['log_sumErr_i'] = df.apply(lambda row: f"{row['log_sumi']:.5f} ± {row['magnitude_err']:.5f}", axis=1)
print(df.log_sumErr_i)

0     -15.76587 ± 0.00084
1     -11.51303 ± 0.01804
2     -11.48126 ± 0.01822
3     -10.94252 ± 0.02912
4     -12.88454 ± 0.00563
5     -13.83549 ± 0.00273
6     -11.45763 ± 0.01862
7     -14.57301 ± 0.00167
8     -13.71674 ± 0.00298
9     -12.19029 ± 0.00990
10    -15.20823 ± 0.00114
11    -14.55396 ± 0.00169
12    -11.33585 ± 0.02111
13    -12.37604 ± 0.00862
Name: log_sumErr_i, dtype: object

# Known Magnitudes Table

In [77]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy import odr

df = pd.read_csv(r"C:\Users\Jonathan Chavez\OneDrive\Desktop\GBO-Calibration\instrumentals.csv",
                 sep=",", encoding='cp1252') #Note: In this CSV file, logarithms are already taken

df.head(14)

      Ra (deg)  Dec (deg)       g   gErr       i   iErr
0   209.397542  -9.752132  11.223  0.020  10.771  0.076
1   209.318113  -9.627305  16.077  0.029  14.936  0.056
2   209.360342  -9.411171  15.534  0.072  14.891  0.064
3   209.344599  -9.354614  16.072  0.057  15.411  0.068
4   209.137084  -9.480872  14.154  0.051  13.547  0.034
5   209.213960  -9.422863  13.238  0.062  12.625  0.034
6   209.246385  -9.409900  15.611  0.060  15.045  0.067
7   209.318917  -9.456286  13.690  0.048  11.862  0.047
8   209.442814  -9.517508  12.974  0.053  12.780  0.520
9   209.482814  -9.414690  14.944  0.062  14.213  0.068
10  209.499338  -9.693505  12.341  0.025  11.313  0.052
11  209.512912  -9.590211  12.507  0.046  11.963  0.041
12  209.173385  -9.611714  15.806  0.072  15.111  0.060
13  209.278555  -9.735194  14.777  0.014  14.074  0.037

In [78]:
df['g_known'] = df.apply(lambda row: f"{row['g']:.5f} ± {row['gErr']:.5f}", axis=1)
print(df.g_known)

0     11.22300 ± 0.02000
1     16.07700 ± 0.02900
2     15.53400 ± 0.07200
3     16.07200 ± 0.05700
4     14.15400 ± 0.05100
5     13.23800 ± 0.06200
6     15.61100 ± 0.06000
7     13.69000 ± 0.04800
8     12.97400 ± 0.05300
9     14.94400 ± 0.06200
10    12.34100 ± 0.02500
11    12.50700 ± 0.04600
12    15.80600 ± 0.07200
13    14.77700 ± 0.01400
Name: g_known, dtype: object

In [79]:
df['i_known'] = df.apply(lambda row: f"{row['i']:.5f} ± {row['iErr']:.5f}", axis=1)
print(df.i_known)

0     10.77100 ± 0.07600
1     14.93600 ± 0.05600
2     14.89100 ± 0.06400
3     15.41100 ± 0.06800
4     13.54700 ± 0.03400
5     12.62500 ± 0.03400
6     15.04500 ± 0.06700
7     11.86200 ± 0.04700
8     12.78000 ± 0.52000
9     14.21300 ± 0.06800
10    11.31300 ± 0.05200
11    11.96300 ± 0.04100
12    15.11100 ± 0.06000
13    14.07400 ± 0.03700
Name: i_known, dtype: object

# Orthogonal Distance Regression Analysis

In [81]:
print(df.log_sumg)

AttributeError: 'DataFrame' object has no attribute 'log_sumg'

In [2]:
import pandas as pd
from scipy.odr import ODR, Model, Data, RealData
import matplotlib.pyplot as plt
import numpy as np

# Data extracted from the images provided by the user
# For the purpose of this example, the 'x' and 'y' are chosen from 'g’' and 'i’' columns respectively,
# and their corresponding errors from 'g’err' and 'i’err'.
# In a real scenario, the 'x' and 'y' should be the variables between which the relationship is to be modeled.

data = {
    'g': [11.223, 16.077, 15.534, 16.072, 14.154, 13.238, 15.611, 13.69, 12.974, 14.944, 12.341, 12.507, 15.806, 14.777],
    'i': [10.771, 14.936, 14.891, 15.411, 13.547, 12.625, 15.045, 11.862, 12.78, 14.213, 11.313, 11.963, 15.111, 14.074],
    'g_err': [0.02, 0.029, 0.072, 0.057, 0.051, 0.062, 0.06, 0.048, 0.053, 0.062, 0.025, 0.046, 0.072, 0.014],
    'i_err': [0.076, 0.056, 0.064, 0.068, 0.034, 0.034, 0.067, 0.047, 0.52, 0.068, 0.052, 0.041, 0.06, 0.037],
}

# Convert the data into a pandas DataFrame
df = pd.DataFrame(data)

# Prepare the data for ODR
x = df['g'] - df['i']
y = df_i['i']
x_err = df_g['g_err']
y_err = df_g['i_err']

# Define a function to model y = mx + c
def linear_func(p, x):
    m, c = p
    return m * x + c

# Create a model for fitting
linear_model = Model(linear_func)

# Create a RealData object using our data
data = RealData(x, y, sx=x_err, sy=y_err)

# Set up ODR with the model and data
odr = ODR(data, linear_model, beta0=[0., 1.])

# Run the regression
out = odr.run()

# Use the in-built pprint method to display results
out.pprint()

# Plot the data with errors and the best fit line
plt.errorbar(x, y, xerr=x_err, yerr=y_err, linestyle='None', marker='o', ecolor='r', capsize=5, label='Data with error bars')
plt.plot(x, out.beta[0] * x + out.beta[1], label='ODR best fit line')

# Add labels and legend
plt.xlabel('g’')
plt.ylabel('i’')
plt.title('Orthogonal Distance Regression')
plt.legend()

# Show the plot
plt.show()

NameError: name 'df_i' is not defined